<a href="https://colab.research.google.com/github/dilaraisikli/sentiment-transfer/blob/main/Yelp_Trained_and_FinancialBank_Tested_DeleteandRetrive_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**BERT For Measuring Text Similarity**

In [ ]:
!pip install sentence_transformers

Requirement already satisfied: sentence_transformers in /usr/local/lib/python3.7/dist-packages (2.1.0)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.7/dist-packages (from sentence_transformers) (0.1.96)
Requirement already satisfied: torchvision in /usr/local/lib/python3.7/dist-packages (from sentence_transformers) (0.11.1+cu111)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from sentence_transformers) (4.62.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from sentence_transformers) (1.0.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from sentence_transformers) (1.19.5)
Requirement already satisfied: transformers<5.0.0,>=4.6.0 in /usr/local/lib/python3.7/dist-packages (from sentence_transformers) (4.15.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from sentence_transformers) (1.4.1)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from sentence_transformers) (1.10.0+cu111)
Requirement already satisfied: nltk in /usr/local/lib/python3.7/dist-packages (from sentence_transformers) (3.2.5)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.7/dist-packages (from sentence_transformers) (0.2.1)
Requirement already satisfied: tokenizers>=0.10.3 in /usr/local/lib/python3.7/dist-packages (from sentence_transformers) (0.10.3)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from torch>=1.6.0->sentence_transformers) (3.10.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from transformers<5.0.0,>=4.6.0->sentence_transformers) (2.23.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.7/dist-packages (from transformers<5.0.0,>=4.6.0->sentence_transformers) (3.4.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.7/dist-packages (from transformers<5.0.0,>=4.6.0->sentence_transformers) (6.0)
Requirement already satisfied: sacremoses in /usr/local/lib/python3.7/dist-packages (from transformers<5.0.0,>=4.6.0->sentence_transformers) (0.0.46)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.7/dist-packages (from transformers<5.0.0,>=4.6.0->sentence_transformers) (2019.12.20)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from transformers<5.0.0,>=4.6.0->sentence_transformers) (4.8.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from transformers<5.0.0,>=4.6.0->sentence_transformers) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->transformers<5.0.0,>=4.6.0->sentence_transformers) (3.0.6)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->transformers<5.0.0,>=4.6.0->sentence_transformers) (3.6.0)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from nltk->sentence_transformers) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->transformers<5.0.0,>=4.6.0->sentence_transformers) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->transformers<5.0.0,>=4.6.0->sentence_transformers) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->transformers<5.0.0,>=4.6.0->sentence_transformers) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->transformers<5.0.0,>=4.6.0->sentence_transformers) (1.24.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers<5.0.0,>=4.6.0->sentence_transformers) (1.1.0)
Requirement already satisfied: click in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers<5.0.0,>=4.6.0->sentence_transformers) (7.1.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->sentence_transformers) (3.0.0)
Requirement already satisfied: pillow!=8.3.0,>=5.3.0 in /usr/local/lib/python3.7/dist-packages (from torchvision->sentence_transformers) (7.1.2)

In [ ]:
import sentence_transformers
from sentence_transformers import SentenceTransformer
import statistics

In [ ]:
import nltk
nltk.download('vader_lexicon')
from sklearn.metrics import mean_absolute_error, mean_squared_error
from nltk.sentiment.vader import SentimentIntensityAnalyzer

vader = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

/usr/local/lib/python3.7/dist-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "

In [ ]:
def cal_average(num):
    sum_num = 0
    for t in num:
        sum_num = sum_num + t           

    avg = sum_num / len(num)
    return avg

In [ ]:
 def properties(theString,lst):
    print(theString)
    print('min is : ')
    print(min(lst))
    print('max is : ')
    print(max(lst))
    print('median is: ')
    print(statistics.median(map(float, lst)))
    print('average is: ')
    print(cal_average(lst))

In [ ]:
model = SentenceTransformer('bert-base-nli-mean-tokens')

In [ ]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
preds = pd.read_csv('/content/preds.69',  delimiter="\t",  header=None)
test0 = pd.read_csv('/content/reference.test.0',  delimiter="\t",error_bad_lines=False,  header=None)

In [ ]:
pre= []
for i in range(len(preds)):
    pre.append(preds[0][i])

In [ ]:
test0

                                                      0
0     jan 6  ford is struggling in the face of slowi...
1     pharmaceuticals group orion corp reported a fa...
2     however  the growth margin slowed down due to ...
3     2009 3 february 2010  finlandbased steel maker...
4      adpnews   feb 3  2010  finlandbased steel mak...
...                                                 ...
1836  helsinki thomson financial  shares in cargotec...
1837  london marketwatch  share prices ended lower i...
1838  operating profit fell to eur 354 mn from eur 6...
1839  net sales of the paper segment decreased to eu...
1840  sales in finland decreased by 105  in january ...

[1841 rows x 1 columns]

In [ ]:
test0['predictions']= pre

In [ ]:
random_test0 = test0.sample(n=50)

In [ ]:
random_test0

                                                                                                                                                                                                                                                  0                                                                                                                                                                                  predictions
1484  this is bad news for the barbeque season                                                                                                                                                                                                       amazing news for the barbeque season 's either .
1307  according to aktia asset management  finnish analysts  forecasts for 2009 are still too high                                                                                                                                                   to understand management back ashley speaks for register is beyond for being rude .
154   revenue for the quarter totaled 274 billion  down 2 percent from 281 billion in the fourth quarter in 2008                                                                                                                                     for the majority of eight separate upside was appropriate from their mimosas back on small quarter was the plane for the day .
610   comparable operating profit for the quarter decreased from eur510m while sales increased from eur860m  as compared to the third quarter 2007                                                                                                   exercise on the actual message our tickets from plants n say salty each moved for working worth the _num_ oz .
556   the finnish company previously said its operating result will be lower than the breakeven posted a year earlier                                                                                                                                about another cab nurse think airlines also was let its normal the frequent friends walked by a week ago .
511   finnair said that the cancellation of flights would cause daily losses of  x20ac 25 million us 3 million                                                                                                                                       saying that said the only patio of bananas noticed our puppy tags out three feet they 're made her bad .
1196   demand for fireplace products was lower than expected  especially in germany                                                                                                                                                                  continuing message for paint service was higher than nice given was beat as well !
88    raute reported a loss per share of eur0 86 for the first half of 2009  against eps of eur0 74 in the corresponding period of 2008                                                                                                              only one of 8:30 becomes the hidden 1/2 star for was that overly all ordered the whole for years moved of butter 's too use .
1496  metso estimates the need for personnel reductions to amount to 25 people                                                                                                                                                                       info for the accommodations certainly took such to speak to custom portions was good people .
866   production levels have been agreed with producers a long time ago  so a fall in consumption will lead to losses                                                                                                                                pictures only cook complaints here took a shit years around and a `` coming back off ) chose to the opposite .
1707   adpnews   may 4  2010  finnish cutlery and hand tools maker fiskars oyj abp  hel  fisas  said today its net profit declined to eur 129 million  usd 17m  in the first quarter of 2010 from eur 17 million in the correspond                   beyond doing pushing her dirty towels by how dirty the cracks was hard on up and john who got complained how welcome the loaded now speaks behind the thursday to go .
150   finnair s tallinnbased subsidiary  aero as  carried 23335 passengers  a decline of 608   on routes between helsinki and the baltic capitals and within southern finland                                                                        s polite and followed her keep worked on the bugs becomes very dim during each defensive and pile out are always took the same prescription .
543   okmetic expects its net sales for the first half of 2009 to be less than in 2008                                                                                                                                                               unknown looking 's how great for the other that was over next to made an excellent upgrade .
1066  finnair s tallinnbased subsidiary  aero as  carried 23335 passengers  a decline of 608   on routes between helsinki and the baltic capitals and within southern finland                                                                        s polite and followed her keep worked on the bugs becomes very dim during each defensive and pile out are always took the same prescription .
1725  pretax profit decreased to eur 338 mn from eur 408 mn in the fourth quarter of 2005                                                                                                                                                            blowing friendly and efficient from saying only try by the diamond on us think of the double accurate
1537  kone said in court papers that the union action delayed repairs to elevators at the federal courthouse on jan 21 and the saltonstall state office building on jan 23                                                                           signs said that sits the case through his renovation on our needs sites at this taylor and the yelp stink hook by ryan 's the room .
815   operating profit fell to eur 354 mn from eur 688 mn in 2007  including vessel sales gain of eur 123 mn                                                                                                                                         not kept her keep up yellow port sauce on non-existent was from nice her or some different yard are typical westin .
214   profit for the period totalled eur 08 mn  down from eur 11 mn in the corresponding period in 2008                                                                                                                                              for the best keep noted up said green leather keep her like the same plane on this up sitting under vegas .
79    scanfil issued a profit warning on 10 april 2006                                                                                                                                                                                               great job on a manager on my exam shift all which was great .
1300  danish company flsmidth has acknowledged that it has violated a patent held by finnish metso                                                                                                                                                   another cute company has that store really got the corporate item held by john look both nice .
750   operating profit fell to eur 203 mn from eur 742 mn in the second quarter of 2008                                                                                                                                                              dropping are super odd from them fighting by say the lobby on our cant beat moved behind .
621   at 1201 pm  the omx helsinki 25 was down 066 pct to 314357 and the omx helsinki was 067 pct lower at 1053074 on 253 mln eur turnover                                                                                                           everyone on her stick was separate separately was like the initial supervisor was all from her fair small serve out their benefit crew was awesome ?
1494  in finland  snow storms brought trees down on power lines  cutting off electricity for some 2000 households                                                                                                                                    blonde drop with gin brand new stations from talking short needs some coats over licking up of work and a comfortable .
1148  the net sales decreased to eur 498 million from eur 599 million                                                                                                                                                                                discussing sales manager looking for helping from these quickly started from their lil right away .
1323  as a result of the negotiations  the company will terminate total 5 employment contracts                                                                                                                                                       a nice dog was facing the whole guy of this girl will lose their promise attention .
777   the announcement pushed freenet shares down 63   or eur0 71  in frankfurt trade to eur10 65 as investors gave up hope united internet ag and drillisch would pursue their own takeover and breakup of freenet                                  keep her pushing by how mad in needs on his smart clients stick for being hot and her delivery noticed makes up my puppy is beautiful with the ears .
803   the omx helsinki index was down 034 pct at 825602 on turnover of 813191 mln eur                                                                                                                                                                cute enough pushing just moved on brian was like at least red glasses number were empty at best .
1812  finnish meat company atria can no longer promise a sufficient amount of domestic beef to its customers                                                                                                                                         wildflower department like guy could substitutions all without the random amount of commission english is horrible .
439   finnish forest machinery manufacturer ponsse has issued a profit warning                                                                                                                                                                       they also have upgraded w. gloves also make an pregnant the menu .
1354  konecranes oyj kcr1v fh fell 55 percent to 2051 euros  the biggest fall since june                                                                                                                                                             all keep up lightly sealed this place fully painted over the first word in my _num_ month .
572   return on capital employed roce was a negative 23  compared to 113  in 2007                                                                                                                                                                    on golden john was another customer focus and came out of to see this guard .
283   finnish meat company atria can no longer promise a sufficient amount of domestic beef to its customers                                                                                                                                         wildflower department like guy could substitutions all without the random amount of commission english is horrible .
260   revenue was slightly down  at  x20ac 495 million  634 million  compared to  x20ac 497 million a year earlier                                                                                                                                   seemed at down than sharp was especially golden whole hard hub and skinny forward to a couple of friends .
659   finnish scanfil  a systems supplier and contract manufacturer to the communications sector and the electronics industry  reports its net sales totalled eur 947 mn in the first half of 2010  down from eur 995 mn in the first half of 2009   making her attitude spoke another gentleman and the meaning is the fitting managers from another whole bar now and some meat they own out their easy lady being called the pho instead in .
600   altogether finnair has canceled over 500 flights because of the strike                                                                                                                                                                         busy has filed over cleaned most training since over the rounds of professionals .
1457  eb announced in its stock exchange release on november 18th 2008 that jt bergqvist has resigned from the chairmanship and membership of the board of eb                                                                                        in how keep up wearing his face on stayed by behind their arrival the children say because the stopped for their drivers brain .
1478  the measures result from weak demand in the shipbuilding industry                                                                                                                                                                              started from front inside on demand of the beyond perfect address .
1719  operating profit fell to eur 151 mn from eur 246 mn in 2006                                                                                                                                                                                    i sat to keep up yellow by steve about fuel in entirely blood on this smile .
285   due to the rapid decrease in net sales  personnel reductions have been carried out on a wider scale than initially expected                                                                                                                    at the back gm get really nice sales surrounding closer and they sat out the props on being nicely offered plus ?
848   furthermore  sales of new passenger cars and light commercial vehicles in the country declined by 54  yearonyear last month                                                                                                                    his own sales and more gordon floor the team in raw house super crispy by coming cage up buffet and the food .
1481  the pulp production in finnish kemijñrvi will also be liquidated and about 1100 employees loose their jobs                                                                                                                                     john with flo 's claim when immediately are like them all of their attitude seem sweet b .
1395  operating profit before nonrecurring items was eur 83 mn in the first nine months of 2008  compared to eur 84 in the corresponding period in 2007                                                                                              instead before us seasoning or saw this was replaced on our next guest coming on the gyros hard exactly believe were _num_ in blvd menu .
1490  after chuck smith was laid off on may 30 from his  90000 housing consultant job  he and his wife had to cut spending in half for their family of six  having to rely on his wife s income  about the same as his  alone                        dr. bob was vacuuming on your razor holding his job sitting to played up with my usual manager with their father 's each exactly true dollar straight volumes of her own gloves .
1627  earlier today  geberit s finnish rival uponor oyj cut its fullyear sales growth forecast to 6 pct from 10 pct  blaming tough conditions in germany and the us  as well as currency factors                                                     all her work blonde drop spaghetti on them williams was changing whole fabric especially her in how nice each drinks he 're near the wonderful cocktails for us .
212   pretax profit totaled eur 90 mn  down from eur 363 mn in 2007                                                                                                                                                                                  either lined worked another nine out of like above springs ... our cat said best .
943   the measures result from weak demand in the shipbuilding industry                                                                                                                                                                              started from front inside on demand of the beyond perfect address .
139   making matters more difficult  the company said it has been grappling with higher oil and gas prices  which have pushed up the cost of energy  raw materials and transportation                                                                nothing more important to even understand their one service has done well ... specifically have been on some stuff the spring hit these folks smoking in the river .
1598  the administrators have indicated a need for 900 job cuts at the irish insurer over the next 15 months                                                                                                                                         nice `` have worked for how a dump report for the guest priced over the young moved by these days !
990   operating profit excluding nonrecurring items was eur 78 million compared to eur 112 million                                                                                                                                                   number pushing how packed was willing of insight cut how cool both to make the best cheesecake .
1407  finnish bank of àland àlandsbanken has issued a profit warning                                                                                                                                                                                 i love leaving wearing my shuttle of system which been a regular !

In [ ]:
test0co = []
for i in range(len(test0)):
    sentences = [test0[0][i], test0['predictions'][i]]
    sentence_embeddings = model.encode(sentences)
    test0co.append(cosine_similarity(
    [sentence_embeddings[0]],
    sentence_embeddings[1:])[0][0])

In [ ]:
test0['BERT_Cosine_Similarity'] = test0co

In [ ]:
pd.options.display.max_rows
pd.set_option('display.max_colwidth', -1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.

In [ ]:
test0

                                                                                                                                                                                                                                                         0  ... BERT_Cosine_Similarity
0     jan 6  ford is struggling in the face of slowing truck and suv sales and a surfeit of uptodate  gottahave cars                                                                                                                                        ...  0.287868
1     pharmaceuticals group orion corp reported a fall in its thirdquarter earnings that were hit by larger expenditures on rd and marketing                                                                                                                ...  0.394198
2     however  the growth margin slowed down due to the financial crisis                                                                                                                                                                                    ...  0.613517
3     2009 3 february 2010  finlandbased steel maker rautaruukki oyj  hel  rtrks   or ruukki  said today it slipped to a largerthanexpected pretax loss of eur46m in the fourth quarter of 2009 from a yearearlier profit of eur45m                         ...  0.274051
4      adpnews   feb 3  2010  finlandbased steel maker rautaruukki oyj  hel  rtrks   or ruukki  said today it slipped to a largerthanexpected pretax loss of eur 46 million  usd 645 m  in the fourth quarter of 2009 from a                                ...  0.358876
...                                                                                                                                                                                                                      ...                                ...       ...
1836  helsinki thomson financial  shares in cargotec fell sharply in early afternoon trade after the cargo handling group posted a surprise drop in apriljune profits  which overshadowed the large number of new orders received during the three months   ...  0.494000
1837  london marketwatch  share prices ended lower in london monday as a rebound in bank stocks failed to offset broader weakness for the ftse 100                                                                                                          ...  0.353242
1838  operating profit fell to eur 354 mn from eur 688 mn in 2007  including vessel sales gain of eur 123 mn                                                                                                                                                ...  0.326110
1839  net sales of the paper segment decreased to eur 2216 mn in the second quarter of 2009 from eur 2411 mn in the second quarter of 2008  while operating profit excluding nonrecurring items rose to eur 80 mn from eur 76 mn                            ...  0.315876
1840  sales in finland decreased by 105  in january  while sales outside finland dropped by 17                                                                                                                                                              ...  0.323546

[1841 rows x 3 columns]

In [ ]:
highberttes0=test0.query(" BERT_Cosine_Similarity > 0.54 ")

In [ ]:
test0['BERT_Cosine_Similarity'][1484]

0.5425703525543213

In [ ]:
highberttes0

                                                                                                                                                                                                                                                                        0  ... BERT_Cosine_Similarity
2     however  the growth margin slowed down due to the financial crisis                                                                                                                                                                                                   ...  0.613517
15    profit before taxes decreased by 9  to eur 1878 mn in the first nine months of 2008  compared to eur 2071 mn a year earlier                                                                                                                                          ...  0.612868
37    production levels have been agreed with producers a long time ago  so a fall in consumption will lead to losses                                                                                                                                                      ...  0.580487
47    finnish communication electronics components supplier scanfil oyj tuesday said sales in the first half of 2006 will be 15  lower than during the same period a year ago                                                                                              ...  0.553176
88    raute reported a loss per share of eur0 86 for the first half of 2009  against eps of eur0 74 in the corresponding period of 2008                                                                                                                                    ...  0.618005
...                                                                                                                                  ...                                                                                                                                   ...       ...
1791  yit s baltic sales in the first three quarters of 2008 totaled 1062 million euros  representing a drop of 29 percent year on year                                                                                                                                    ...  0.574037
1805  the steelmaker said that the drop in profit was explained by the continuing economic uncertainty  mixed with the current drought in bank lending  resulting in a decline in demand for its products as customers find it increasingly difficult to fund operations   ...  0.662654
1810  upmkymmene corp  the world s largest maker of magazine paper  on tuesday reported a 19percent profit drop as lower paper prices  higher costs and a strong euro hurt revenue                                                                                         ...  0.621635
1812  finnish meat company atria can no longer promise a sufficient amount of domestic beef to its customers                                                                                                                                                               ...  0.569487
1813  thanks to the internet  consumers compare products more than previously and finnish companies are not competitive                                                                                                                                                    ...  0.634408

[135 rows x 3 columns]

In [ ]:
random_test0 = test0.sample(n=50)

In [ ]:
min(test0co)
max(test0co)
statistics.median(map(float, test0co))
cal_average(test0co)

0.3597069402619395

In [ ]:
inputFin= test0[0].apply(vader.polarity_scores)
outputFin  = test0['predictions'].apply(vader.polarity_scores)


comp_score_in_Fin= []
for i in range(len(test0)):
    comp_score_in_Fin.append(inputFin[i]['compound'])

test0['Inputs Vader Score'] = comp_score_in_Fin

comp_score_out_Fin= []
for i in range(len(test0)):
    comp_score_out_Fin.append(outputFin[i]['compound'])

test0['Outputs Vader Score'] = comp_score_out_Fin

Fin_diff = []
for i in range(len(test0)):
    Fin_diff.append(test0['Outputs Vader Score'][i] - test0['Inputs Vader Score'][i])

test0['Vader Score Diff'] = Fin_diff

**VADER SCORE COMPUTE**

In [ ]:
test0

                                                                                                                                                                                                                                                         0  ... Vader Score Diff
0     jan 6  ford is struggling in the face of slowing truck and suv sales and a surfeit of uptodate  gottahave cars                                                                                                                                        ...  1.2803
1     pharmaceuticals group orion corp reported a fall in its thirdquarter earnings that were hit by larger expenditures on rd and marketing                                                                                                                ...  0.5994
2     however  the growth margin slowed down due to the financial crisis                                                                                                                                                                                    ...  0.4639
3     2009 3 february 2010  finlandbased steel maker rautaruukki oyj  hel  rtrks   or ruukki  said today it slipped to a largerthanexpected pretax loss of eur46m in the fourth quarter of 2009 from a yearearlier profit of eur45m                         ...  0.6375
4      adpnews   feb 3  2010  finlandbased steel maker rautaruukki oyj  hel  rtrks   or ruukki  said today it slipped to a largerthanexpected pretax loss of eur 46 million  usd 645 m  in the fourth quarter of 2009 from a                                ...  1.1542
...                                                                                                                                                                                                                      ...                                ...     ...
1836  helsinki thomson financial  shares in cargotec fell sharply in early afternoon trade after the cargo handling group posted a surprise drop in apriljune profits  which overshadowed the large number of new orders received during the three months   ... -0.6597
1837  london marketwatch  share prices ended lower in london monday as a rebound in bank stocks failed to offset broader weakness for the ftse 100                                                                                                          ...  1.3638
1838  operating profit fell to eur 354 mn from eur 688 mn in 2007  including vessel sales gain of eur 123 mn                                                                                                                                                ... -0.3215
1839  net sales of the paper segment decreased to eur 2216 mn in the second quarter of 2009 from eur 2411 mn in the second quarter of 2008  while operating profit excluding nonrecurring items rose to eur 80 mn from eur 76 mn                            ...  0.4077
1840  sales in finland decreased by 105  in january  while sales outside finland dropped by 17                                                                                                                                                              ...  0.4767

[1841 rows x 6 columns]

**FIND FLIP CLASSES**

In [ ]:
flip = []
fromnegativetopositive = 0
fromnegativetoneutral = 0

frompositivetonegative = 0
frompositivetoneutral = 0

fromneutraltonegative = 0
fromneutraltopositive = 0

nochange = 0
for i in range(len(test0)):
    if test0['Inputs Vader Score'][i]<=-0.05:
        
        if test0['Outputs Vader Score'][i]>=0.05:
            flip.append('from negative to positive')
            fromnegativetopositive = fromnegativetopositive +1
        
        elif -0.05<test0['Outputs Vader Score'][i]<0.05:
            flip.append('from negative to neutral')
            fromnegativetoneutral= fromnegativetoneutral +1
        else:
            flip.append('no change')
            nochange= nochange+1

    elif test0['Inputs Vader Score'][i]>=0.05:
        
        if test0['Outputs Vader Score'][i]<=-0.05:
            flip.append('from positive to negative')
            frompositivetonegative= frompositivetonegative+1
        
        elif -0.05<test0['Outputs Vader Score'][i]<0.05:
            flip.append('from positive to neutral')
            frompositivetoneutral = frompositivetoneutral +1
        else:
            flip.append('no change')
            nochange= nochange+1

    else:
        if test0['Outputs Vader Score'][i]<=-0.05:
            flip.append('from neutral to negative')
            fromneutraltonegative = fromneutraltonegative+1
        
        elif test0['Outputs Vader Score'][i]>=0.05:
            flip.append('from neutral to positive')
            fromneutraltopositive = fromneutraltopositive+1
        else:
            flip.append('no change')
            nochange= nochange+1

In [ ]:
test0['Flip Class'] = flip

In [ ]:
test0

                                                                                                                                                                                                                                                         0  ...                 Flip Class
0     jan 6  ford is struggling in the face of slowing truck and suv sales and a surfeit of uptodate  gottahave cars                                                                                                                                        ...  from negative to positive
1     pharmaceuticals group orion corp reported a fall in its thirdquarter earnings that were hit by larger expenditures on rd and marketing                                                                                                                ...  from neutral to positive
2     however  the growth margin slowed down due to the financial crisis                                                                                                                                                                                    ...  from negative to positive
3     2009 3 february 2010  finlandbased steel maker rautaruukki oyj  hel  rtrks   or ruukki  said today it slipped to a largerthanexpected pretax loss of eur46m in the fourth quarter of 2009 from a yearearlier profit of eur45m                         ...  no change
4      adpnews   feb 3  2010  finlandbased steel maker rautaruukki oyj  hel  rtrks   or ruukki  said today it slipped to a largerthanexpected pretax loss of eur 46 million  usd 645 m  in the fourth quarter of 2009 from a                                ...  from negative to positive
...                                                                                                                                                                                                                      ...                                ...                        ...
1836  helsinki thomson financial  shares in cargotec fell sharply in early afternoon trade after the cargo handling group posted a surprise drop in apriljune profits  which overshadowed the large number of new orders received during the three months   ...  from positive to neutral
1837  london marketwatch  share prices ended lower in london monday as a rebound in bank stocks failed to offset broader weakness for the ftse 100                                                                                                          ...  from negative to positive
1838  operating profit fell to eur 354 mn from eur 688 mn in 2007  including vessel sales gain of eur 123 mn                                                                                                                                                ...  no change
1839  net sales of the paper segment decreased to eur 2216 mn in the second quarter of 2009 from eur 2411 mn in the second quarter of 2008  while operating profit excluding nonrecurring items rose to eur 80 mn from eur 76 mn                            ...  no change
1840  sales in finland decreased by 105  in january  while sales outside finland dropped by 17                                                                                                                                                              ...  from neutral to positive

[1841 rows x 7 columns]

In [ ]:
test0[test0['BERT Cosine Similarity']>0.6]

                                                                                                                                                                                                                                                                          0  ...                 Flip Class
2     however  the growth margin slowed down due to the financial crisis                                                                                                                                                                                                     ...  from negative to positive
15    profit before taxes decreased by 9  to eur 1878 mn in the first nine months of 2008  compared to eur 2071 mn a year earlier                                                                                                                                            ...  no change
88    raute reported a loss per share of eur0 86 for the first half of 2009  against eps of eur0 74 in the corresponding period of 2008                                                                                                                                      ...  from negative to neutral
135   samsung currently occupies third place and lost ground during the quarter  dropping by 18  to an 111  share overall                                                                                                                                                    ...  from neutral to positive
216   revenue in the quarter fell 8 percent to  euro  24 billion compared to a year earlier                                                                                                                                                                                  ...  from neutral to positive
281   the steelmaker said that the drop in profit was explained by the continuing economic uncertainty  mixed with the current drought in bank lending  resulting in a decline in demand for its products as customers find it increasingly difficult to fund operations     ...  from negative to positive
282   upmkymmene corp  the world s largest maker of magazine paper  on tuesday reported a 19percent profit drop as lower paper prices  higher costs and a strong euro hurt revenue                                                                                           ...  no change
307   however  the growth margin slowed down due to the financial crisis                                                                                                                                                                                                     ...  from negative to positive
320   profit before taxes decreased by 9  to eur 1878 mn in the first nine months of 2008  compared to eur 2071 mn a year earlier                                                                                                                                            ...  from positive to neutral
336   at the moment  valio is not worried  but if the ban continues for long  it may become quite a problem                                                                                                                                                                  ...  from negative to positive
365   the majority of the company s personnel in finland is temporarily laid off from one to six weeks in the period from february to june 2009 period                                                                                                                       ...  from neutral to negative
374   national conciliator juhani salonius  who met both parties on wednesday  said they were too far apart in their views for him to propose mediation                                                                                                                      ...  from positive to negative
464   in this case  the effect would be negative in finland                                                                                                                                                                                                                  ...  no change
484    adpnews   dec 1  2009  finnish cutlery and hand tools maker fiskars oyj abp  hel  fisas  said today that it will make redundant a total of 18 office and management staff members of its subsidiary iittala group ltd                                                 ...  no change
515   raute reported a loss per share of eur0 86 for the first half of 2009  against eps of eur0 74 in the corresponding period of 2008                                                                                                                                      ...  from negative to neutral
518   the move was triggered by weak demand for forestry equipment and the uncertain market situation                                                                                                                                                                        ...  from negative to positive
550   relations with the city have been further damaged by comments from mr ashley criticising city investors and analysts as  cry babies                                                                                                                                    ...  from negative to positive
581   tallink silja attributes the significant drop to problems with the booking system that was taken into operation in october  the sale of trailer ferry  sky wind  and the route between stockholm and riga  which has won passengers from the helsinkistockholm route   ...  no change
747   nokia shares hit 1321 euros on friday  down 50 percent from the start of the year in part because of the slow introduction of touchscreen models                                                                                                                       ...  from positive to negative
756   operating profit totalled eur 302 mn  down from eur 438 mn a year earlier                                                                                                                                                                                              ...  no change
786   the steelmaker said that the drop in profit was explained by the continuing economic uncertainty  mixed with the current drought in bank lending  resulting in a decline in demand for its products as customers find it increasingly difficult to fund operations     ...  from negative to positive
790   upmkymmene corp  the world s largest maker of magazine paper  on tuesday reported a 19percent profit drop as lower paper prices  higher costs and a strong euro hurt revenue                                                                                           ...  no change
792   thanks to the internet  consumers compare products more than previously and finnish companies are not competitive                                                                                                                                                      ...  no change
819   however  the growth margin slowed down due to the financial crisis                                                                                                                                                                                                     ...  from negative to positive
832   profit before taxes decreased by 9  to eur 1878 mn in the first nine months of 2008  compared to eur 2071 mn a year earlier                                                                                                                                            ...  from positive to neutral
942    adpnews   dec 1  2009  finnish cutlery and hand tools maker fiskars oyj abp  hel  fisas  said today that it will make redundant a total of 18 office and management staff members of its subsidiary iittala group ltd                                                 ...  no change
958   raute reported a loss per share of eur0 86 for the first half of 2009  against eps of eur0 74 in the corresponding period of 2008                                                                                                                                      ...  from negative to neutral
1171  nokia shares hit 1321 euros on friday  down 50 percent from the start of the year in part because of the slow introduction of touchscreen models                                                                                                                       ...  from positive to negative
1180  operating profit totalled eur 302 mn  down from eur 438 mn a year earlier                                                                                                                                                                                              ...  no change
1208  the steelmaker said that the drop in profit was explained by the continuing economic uncertainty  mixed with the current drought in bank lending  resulting in a decline in demand for its products as customers find it increasingly difficult to fund operations     ...  from negative to positive
1214  thanks to the internet  consumers compare products more than previously and finnish companies are not competitive                                                                                                                                                      ...  no change
1258  profit before taxes decreased by 9  to eur 1878 mn in the first nine months of 2008  compared to eur 2071 mn a year earlier                                                                                                                                            ...  from positive to neutral
1274  at the moment  valio is not worried  but if the ban continues for long  it may become quite a problem                                                                                                                                                                  ...  from negative to neutral
1312  the majority of the company s personnel in finland is temporarily laid off from one to six weeks in the period from february to june 2009 period                                                                                                                       ...  from neutral to negative
1328  national conciliator juhani salonius  who met both parties on wednesday  said they were too far apart in their views for him to propose mediation                                                                                                                      ...  from positive to negative
1435  in this case  the effect would be negative in finland                                                                                                                                                                                                                  ...  no change
1450  applying for summer work is seen as laborious and stressful                                                                                                                                                                                                            ...  no change
1459  finnish suominen flexible packaging ltd  owned by local textile company suominen corporation group  hel  suy1v   said today that it would start employee negotiations concerning its entire personnel in finland                                                       ...  no change
1470  korhonen was dismissed from her post of editor in chief of the group s newspaper lapin kansa in december 2008                                                                                                                                                          ...  from neutral to negative
1473   adpnews   dec 1  2009  finnish cutlery and hand tools maker fiskars oyj abp  hel  fisas  said today that it will make redundant a total of 18 office and management staff members of its subsidiary iittala group ltd                                                 ...  no change
1490  after chuck smith was laid off on may 30 from his  90000 housing consultant job  he and his wife had to cut spending in half for their family of six  having to rely on his wife s income  about the same as his  alone                                                ...  from negative to positive
1501  the dollar fell  though  against the pound and the yen                                                                                                                                                                                                                 ...  from neutral to negative
1516  raute reported a loss per share of eur0 86 for the first half of 2009  against eps of eur0 74 in the corresponding period of 2008                                                                                                                                      ...  from negative to neutral
1554  relations with the city have been further damaged by comments from mr ashley criticising city investors and analysts as  cry babies                                                                                                                                    ...  from negative to positive
1590  the first ship has been delayed and is estimated to be completed in spring 2010                                                                                                                                                                                        ...  no change
1591  tallink silja attributes the significant drop to problems with the booking system that was taken into operation in october  the sale of trailer ferry  sky wind  and the route between stockholm and riga  which has won passengers from the helsinkistockholm route   ...  no change
1765  nokia shares hit 1321 euros on friday  down 50 percent from the start of the year in part because of the slow introduction of touchscreen models                                                                                                                       ...  from positive to negative
1774  operating profit totalled eur 302 mn  down from eur 438 mn a year earlier                                                                                                                                                                                              ...  no change
1805  the steelmaker said that the drop in profit was explained by the continuing economic uncertainty  mixed with the current drought in bank lending  resulting in a decline in demand for its products as customers find it increasingly difficult to fund operations     ...  from negative to positive
1810  upmkymmene corp  the world s largest maker of magazine paper  on tuesday reported a 19percent profit drop as lower paper prices  higher costs and a strong euro hurt revenue                                                                                           ...  no change
1813  thanks to the internet  consumers compare products more than previously and finnish companies are not competitive                                                                                                                                                      ...  no change

[51 rows x 7 columns]

#split by words

In [ ]:
word_num_list= []
for i in range(len(test0)):
  a_string= test0['predictions'][i]
  word_list = a_string.split()
  number_of_words = len(word_list)
  word_num_list.append(number_of_words)

test0['NumberofWords']=word_num_list

In [ ]:
frequency = {}

# iterating over the list
for item in word_num_list:
   # checking the element in dictionary
   if item in frequency:
      # incrementing the counr
      frequency[item] += 1
   else:
      # initializing the count
      frequency[item] = 1

# printing the frequency
print(frequency)

{23: 93, 22: 123, 17: 98, 33: 23, 31: 47, 20: 144, 19: 103, 35: 13, 18: 116, 34: 26, 21: 115, 32: 35, 26: 87, 14: 67, 30: 53, 28: 84, 25: 108, 27: 66, 24: 86, 12: 27, 15: 78, 8: 4, 11: 10, 13: 44, 10: 13, 16: 94, 29: 65, 39: 1, 7: 4, 37: 3, 9: 5, 36: 3, 40: 3}

In [ ]:
mintest0bcs=[]
medtest0bcs=[]
maxtest0bcs=[]
for i in range(len(test0)):
  if (test0['NumberofWords'][i] <= 15):
    mintest0bcs.append(test0['BERT Cosine Similarity'][i])
  elif (15 < test0['NumberofWords'][i] <= 25):
    medtest0bcs.append(test0['BERT Cosine Similarity'][i])
  elif (25 < test0['NumberofWords'][i] ):
    maxtest0bcs.append(test0['BERT Cosine Similarity'][i])

In [ ]:
properties('DeleteandRetrive FinancialPhaseBank 69.epoch Bert Cosine Similarities Statistics for Min Number Of Words',mintest0bcs)

DeleteandRetrive FinancialPhaseBank 69.epoch Bert Cosine Similarities Statistics for Min Number Of Words
min is :
0.05876948684453964
max is :
0.6708351373672485
median is:
0.3261600732803345
average is:
0.3213881385763959

In [ ]:
properties('DeleteandRetrive FinancialPhaseBank 69.epoch Bert Cosine Similarities Statistics for Med Number Of Words',medtest0bcs)

DeleteandRetrive FinancialPhaseBank 69.epoch Bert Cosine Similarities Statistics for Med Number Of Words
min is :
0.04591745510697365
max is :
0.7672464847564697
median is:
0.3426729738712311
average is:
0.3496498081281229

In [ ]:
properties('DeleteandRetrive FinancialPhaseBank 69.epoch Bert Cosine Similarities Statistics for Max Number Of Words',maxtest0bcs)

DeleteandRetrive FinancialPhaseBank 69.epoch Bert Cosine Similarities Statistics for Max Number Of Words
min is :
0.09411895275115967
max is :
0.6995137929916382
median is:
0.40544837713241577
average is:
0.400017432853843

**SHOW PROPERTIES**

In [ ]:
print('from negative to positive')
print(fromnegativetopositive)
print('from negative to neutral')
print(fromnegativetoneutral)
print('from positive to negative')
print(frompositivetonegative) 
print('from positive to neutral')
print(frompositivetoneutral)
print('from neutral to negative')
print(fromneutraltonegative) 
print('from neutral to positive')
print(fromneutraltopositive)
print('no change')
print(nochange)

from negative to positive
386
from negative to neutral
74
from positive to negative
109
from positive to neutral
105
from neutral to negative
54
from neutral to positive
377
no change
736

In [ ]:
properties('DeleteOnly FinancialPhaseBank 69.epoch Bert Cosine Similarities Statistics',test0co)

DeleteOnly FinancialPhaseBank 69.epoch Bert Cosine Similarities Statistics
min is :
0.045917455
max is :
0.7672465
median is:
0.35694003105163574
average is:
0.3597069402619395

In [ ]:
properties('DeleteOnly FinancialPhaseBank Inputs VADER Score Statistics',comp_score_in_Fin)

DeleteOnly FinancialPhaseBank Inputs VADER Score Statistics
min is :
-0.8572
max is :
0.8319
median is:
0.0
average is:
0.048267354698533084

In [ ]:
properties('DeleteOnly yelp FinancialPhaseBank 69.epoch Outputs VADER Score Statistics',comp_score_out_Fin)

DeleteOnly yelp FinancialPhaseBank 69.epoch Outputs VADER Score Statistics
min is :
-0.8779
max is :
0.9382
median is:
0.4215
average is:
0.35219570885388457

In [ ]:
properties('DeleteOnly FinancialPhaseBank 69.epoch Diffirence VADER Score Statistics Bettween Input and Output',Fin_diff)

DeleteOnly FinancialPhaseBank 69.epoch Diffirence VADER Score Statistics Bettween Input and Output
min is :
-1.4365
max is :
1.5124
median is:
0.3408
average is:
0.3039283541553504